In [3]:
import numpy as np
j=[4,6,2,8,9]

In [5]:
1)numpy                   :  Array Operations
2)pandas                  :  Data manipulation and Analysis
3)matplotlib and seaborn  :  Graphical Analysis
4)sklearn                 :  Machine learning algorithms and Techniques
5)statmodels              :  Statical analysis
6)scipy                   :  Statical analysis

SyntaxError: unmatched ')' (1358297516.py, line 1)

In [7]:
j=[4,6,2,8,9,5]
j

[4, 6, 2, 8, 9, 5]

In [9]:
d=np.array(j)
d

array([4, 6, 2, 8, 9, 5])

In [11]:
type(d)

numpy.ndarray

In [13]:
tuple(j)

(4, 6, 2, 8, 9, 5)

In [15]:
d

array([4, 6, 2, 8, 9, 5])

In [17]:
np.mean(d)

5.666666666666667

In [19]:
np.median(d)

5.5

In [21]:
np.var(d)

5.5555555555555545

In [24]:
np.min(d)

2

In [27]:
np.max(d)

9

In [37]:
np.quantile(d,0.25) #quantile=25%

4.25

In [39]:
np.quantile(d,0.05)

2.5

In [41]:
np.quantile(d,0.75)

7.5

In [45]:
r=np.random.rand()
r

0.11917455109032726

In [49]:
r=np.random.rand(100)
r

array([0.20399211, 0.43342424, 0.83400926, 0.16547238, 0.26203152,
       0.30472914, 0.54247093, 0.67032145, 0.91012684, 0.38535834,
       0.43573928, 0.79268296, 0.66243218, 0.64383816, 0.09522769,
       0.51698869, 0.54241572, 0.52972818, 0.02274133, 0.77302297,
       0.100201  , 0.76929428, 0.32931014, 0.92618058, 0.95168497,
       0.16000384, 0.67549463, 0.71599937, 0.65641054, 0.01987439,
       0.84105002, 0.31798151, 0.10407154, 0.82138659, 0.71186885,
       0.86378224, 0.64787673, 0.95448907, 0.847635  , 0.479597  ,
       0.60221512, 0.7195567 , 0.90359233, 0.26801523, 0.66213486,
       0.01707249, 0.34635517, 0.37798039, 0.18142385, 0.12592698,
       0.73489577, 0.45659013, 0.9275225 , 0.77568327, 0.63165397,
       0.2977214 , 0.44608528, 0.64843519, 0.84774325, 0.03168779,
       0.8464138 , 0.11237591, 0.41015262, 0.80562633, 0.17343228,
       0.90164352, 0.92664543, 0.41852144, 0.34318911, 0.73845039,
       0.44710052, 0.01938271, 0.11028093, 0.08477914, 0.00497

In [51]:
r.shape

(100,)

In [53]:
r.size

100

In [55]:
r.ndim

1

In [64]:
r=np.random.rand(5,3)
r

array([[0.87067861, 0.51054541, 0.88765283],
       [0.71225742, 0.03901784, 0.21942911],
       [0.98117959, 0.85374053, 0.1163579 ],
       [0.78951725, 0.45187451, 0.3111077 ],
       [0.5571776 , 0.39776234, 0.41337921]])

In [68]:
r=np.random.rand(5,3,2)
r

array([[[0.90741699, 0.29082839],
        [0.35914328, 0.26614417],
        [0.81560216, 0.07053782]],

       [[0.27714359, 0.62946286],
        [0.20389952, 0.47201538],
        [0.7189383 , 0.29161382]],

       [[0.2217781 , 0.95812286],
        [0.76832693, 0.81467677],
        [0.09618356, 0.99789277]],

       [[0.60508703, 0.28471952],
        [0.8291631 , 0.13590611],
        [0.57906992, 0.51036844]],

       [[0.2191812 , 0.89100926],
        [0.84058738, 0.54015783],
        [0.86071864, 0.74750139]]])

In [71]:
np.random.normal(10,2,(4,5))

array([[10.85330162, 12.7169777 ,  7.91920977, 12.24673489,  6.38766907],
       [ 8.64050547, 11.62415163,  9.08951195, 12.90121753, 12.2422206 ],
       [13.06491145,  8.4054379 , 10.44288416, 10.19343118, 10.40558598],
       [10.80859177,  9.27132344, 13.26651204, 12.11245238,  9.02114252]])

In [73]:
np.random.normal(40,5,(7,4))

array([[33.5080926 , 41.70497548, 42.98013548, 46.71254911],
       [42.04034558, 38.74463252, 29.83644638, 41.87053777],
       [49.80456725, 39.3205691 , 33.79679428, 45.04710062],
       [30.52557515, 34.7300782 , 44.12758728, 37.64014948],
       [40.69996523, 32.60359857, 38.86467804, 42.70120189],
       [36.79460257, 35.13537324, 44.20296424, 36.14072009],
       [38.61357706, 39.73408471, 44.05896778, 47.16994381]])

In [81]:
np.random.randint(35,86,200)

array([69, 84, 42, 48, 61, 75, 37, 75, 43, 73, 79, 44, 74, 80, 47, 70, 76,
       71, 52, 38, 61, 36, 84, 63, 48, 47, 64, 83, 46, 78, 74, 55, 80, 85,
       56, 64, 66, 79, 43, 35, 39, 75, 45, 75, 51, 72, 55, 43, 65, 48, 78,
       36, 64, 47, 46, 48, 67, 42, 61, 35, 56, 74, 80, 67, 39, 85, 47, 76,
       75, 69, 63, 82, 71, 44, 75, 61, 63, 78, 38, 71, 50, 36, 47, 84, 40,
       38, 52, 46, 74, 41, 43, 83, 58, 67, 63, 63, 38, 44, 38, 66, 59, 55,
       85, 45, 63, 77, 42, 59, 48, 82, 38, 60, 57, 36, 80, 76, 63, 62, 69,
       55, 80, 71, 80, 69, 82, 47, 83, 60, 85, 61, 42, 48, 46, 38, 45, 67,
       50, 65, 84, 42, 75, 57, 84, 41, 53, 78, 54, 52, 47, 57, 49, 50, 53,
       69, 85, 63, 36, 82, 47, 81, 74, 56, 70, 51, 82, 66, 50, 52, 67, 35,
       43, 78, 71, 58, 37, 47, 79, 45, 40, 60, 72, 47, 81, 63, 69, 67, 64,
       44, 45, 57, 53, 39, 41, 76, 55, 67, 73, 85, 72, 73])

In [83]:
np.random.randint(35,86,5)

array([47, 76, 36, 82, 41])

In [85]:
np.random.randint(35,86,(5,5))

array([[58, 47, 69, 48, 35],
       [46, 55, 70, 40, 72],
       [64, 36, 84, 64, 69],
       [58, 53, 74, 71, 64],
       [39, 63, 47, 66, 85]])

In [75]:
d.size

6

In [96]:
d.reshape(3,2)

array([[4, 6],
       [2, 8],
       [9, 5]])

In [102]:
w=d.reshape(3,2)
w

array([[4, 6],
       [2, 8],
       [9, 5]])

In [104]:
w.shape

(3, 2)

In [106]:
w.size

6

In [108]:
w.ndim

2

In [98]:
h=d.reshape(2,3)
h

array([[4, 6, 2],
       [8, 9, 5]])

In [92]:
h.ndim

2

In [94]:
h.size

6

In [5]:
s=[[4,8,90,12],[56,78,54,20],[67,89,50,49],[77,88,22,55],[90,40,70,60]]
s

[[4, 8, 90, 12],
 [56, 78, 54, 20],
 [67, 89, 50, 49],
 [77, 88, 22, 55],
 [90, 40, 70, 60]]

In [7]:
type(s)

list

In [9]:
import numpy as np
arr1=np.array(s)
s

[[4, 8, 90, 12],
 [56, 78, 54, 20],
 [67, 89, 50, 49],
 [77, 88, 22, 55],
 [90, 40, 70, 60]]

In [11]:
arr1.shape

(5, 4)

In [13]:
arr1.size

20

In [15]:
arr1.ndim

2

In [17]:
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [19]:
k=arr1.reshape(2,2,5)
k

array([[[ 4,  8, 90, 12, 56],
        [78, 54, 20, 67, 89]],

       [[50, 49, 77, 88, 22],
        [55, 90, 40, 70, 60]]])

In [21]:
k.size

20

In [23]:
k.ndim

3

In [25]:
k.shape

(2, 2, 5)

In [27]:
y=arr1.reshape(20,)
y

array([ 4,  8, 90, 12, 56, 78, 54, 20, 67, 89, 50, 49, 77, 88, 22, 55, 90,
       40, 70, 60])

In [29]:
y.ndim

1

In [31]:
y.shape

(20,)

In [33]:
y.size

20

In [35]:
z=arr1.reshape(20,1)
z

array([[ 4],
       [ 8],
       [90],
       [12],
       [56],
       [78],
       [54],
       [20],
       [67],
       [89],
       [50],
       [49],
       [77],
       [88],
       [22],
       [55],
       [90],
       [40],
       [70],
       [60]])

In [37]:
z.ndim

2

In [39]:
z=arr1.reshape(1,20)
z

array([[ 4,  8, 90, 12, 56, 78, 54, 20, 67, 89, 50, 49, 77, 88, 22, 55,
        90, 40, 70, 60]])

In [42]:
arr1.shape


(5, 4)

In [44]:
arr1.reshape(2,2,5,1)

array([[[[ 4],
         [ 8],
         [90],
         [12],
         [56]],

        [[78],
         [54],
         [20],
         [67],
         [89]]],


       [[[50],
         [49],
         [77],
         [88],
         [22]],

        [[55],
         [90],
         [40],
         [70],
         [60]]]])

In [46]:
arr1.reshape(2,2,5,1,1)

array([[[[[ 4]],

         [[ 8]],

         [[90]],

         [[12]],

         [[56]]],


        [[[78]],

         [[54]],

         [[20]],

         [[67]],

         [[89]]]],



       [[[[50]],

         [[49]],

         [[77]],

         [[88]],

         [[22]]],


        [[[55]],

         [[90]],

         [[40]],

         [[70]],

         [[60]]]]])

In [48]:
arr1.reshape(1,2,1,2,5,1)

array([[[[[[ 4],
           [ 8],
           [90],
           [12],
           [56]],

          [[78],
           [54],
           [20],
           [67],
           [89]]]],



        [[[[50],
           [49],
           [77],
           [88],
           [22]],

          [[55],
           [90],
           [40],
           [70],
           [60]]]]]])

In [50]:
range(5,20)

range(5, 20)

In [56]:
m=[3,4,5,6,7,8,9,10,11,12]
m

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [58]:
list(range(3,13))

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [60]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [62]:
range(5,500)

range(5, 500)

In [64]:
tuple(range(5,500))

(5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 1

In [66]:
tuple(range(5,500,100))

(5, 105, 205, 305, 405)

In [68]:
tuple(range(5,506,100))

(5, 105, 205, 305, 405, 505)

In [70]:
tuple(range(-10,1))

(-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0)

In [72]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [74]:
(range(-1,-10))

range(-1, 10)

In [76]:
tuple(range(-1,-10,-1))

(-1, -2, -3, -4, -5, -6, -7, -8, -9)

In [78]:
tuple(range(-1,-10,-2))

(-1, -3, -5, -7, -9)

In [80]:
tuple(range(10,-10,-2))

(10, 8, 6, 4, 2, 0, -2, -4, -6, -8)

In [82]:
q=[2.5,3,3.5,4,4.5,]
q

[2.5, 3, 3.5, 4, 4.5]

In [88]:
np.arange(2.5,5,0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [90]:
range(5,50,5)

range(5, 50, 5)

In [94]:
for i in range(5,50,5):
  print("Data",i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [96]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [98]:
y=[]
x=[]
for i in range(len(j)):
    if i%2==0:
        x.append(j[i])
    else:
        y.append(j[i])

In [100]:
x

[5, 23, 62, 80, 77, 80]

In [102]:
y

[87, 46, 84, 45, 33]

In [104]:
for i in j:
    print(j)

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]


In [106]:
for i in j:
    print(i)

5
87
23
46
62
84
80
45
77
33
80


In [108]:
range(len(j))

range(0, 11)

In [110]:
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [118]:
for i in range(len(j)):
            print(i)

0
1
2
3
4
5
6
7
8
9
10
