In [1]:
import numpy as np


In [3]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [32]:
d=[]
for i in h:
    d.append(i+7)
print(d)

[37, 27, 12, 15, 16]


In [63]:
t=(6,2,3,9,7,5,8)
t

(6, 2, 3, 9, 7, 5, 8)

In [71]:
y=list(t)
k=[]
for i in y:
    k.append(i**2)
    t=tuple(k)
print(t)

(1679616, 256, 6561, 43046721, 5764801, 390625, 16777216)


In [87]:
m=[]
for i in t:
    if i>50:
        m.append(i)

In [89]:
m

[1679616, 256, 6561, 43046721, 5764801, 390625, 16777216]

In [91]:
arr=np.array([20,50,30,70,80,40,36,54,26,98])

In [93]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 26, 98])

In [101]:
q=arr+7 # adding an 7 to array
q

array([ 27,  57,  37,  77,  87,  47,  43,  61,  33, 105])

In [103]:
arr*5 # multiplying an array with 5

array([100, 250, 150, 350, 400, 200, 180, 270, 130, 490])

In [109]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 26, 98])

In [111]:
arr>50

array([False, False, False,  True,  True, False, False,  True, False,
        True])

In [131]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 26, 98])

In [137]:
arr[arr>50]

array([70, 80, 54, 98])

In [141]:
arr[arr>+50]

array([70, 80, 54, 98])

In [143]:
arr[arr>=50]

array([50, 70, 80, 54, 98])

In [147]:
arr[arr<50]

array([20, 30, 40, 36, 26])

In [159]:
arr[arr<=50]

array([20, 50, 30, 40, 36, 26])

In [162]:
v=[36,4,9,81,49,25,64]
v

[36, 4, 9, 81, 49, 25, 64]

In [175]:
index=[]
for i in range(len(v)):
    if v[i]>50:
        index.append(i)
index        

[3, 6]

In [177]:
index=[]
for i in range(len(v)):
    if v[i]>20:
        index.append(i)
index        

[0, 3, 4, 5, 6]

In [183]:
arr[arr>50] #elements satisifying condition

array([70, 80, 54, 98])

In [179]:
np.where(arr>50) #indexes of elements satisifying condition

(array([3, 4, 7, 9], dtype=int64),)

In [181]:
np.where(arr>20)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)