In [7]:
import pandas as pd
import numpy as np

In [9]:
a=np.random.randint(20,60,15)
a

array([54, 52, 26, 27, 41, 21, 44, 34, 57, 23, 40, 57, 48, 36, 36])

In [11]:
a[0]

54

In [13]:
a[7]

34

In [15]:
a[-4]

57

In [17]:
a[-5:-12:-1]


array([40, 23, 57, 34, 44, 21, 41])

In [19]:
a.ndim

1

In [21]:
np.random.seed(94)
b=np.random.randint(45,78,(7,8))
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [23]:
b[2] # 2nd row

array([71, 56, 51, 58, 59, 47, 68, 77])

In [25]:
b[:,7] # 7th column

array([53, 60, 77, 55, 51, 47, 61])

In [27]:
b[1,3]

77

In [29]:
b[:,3]

array([67, 77, 58, 74, 69, 77, 69])

In [31]:
b[5,6]

67

In [33]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [35]:
b[2]

array([71, 56, 51, 58, 59, 47, 68, 77])

In [37]:
b[2,1:6]

array([56, 51, 58, 59, 47])

In [41]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [ ]:
## "array[row_start:row-end:row-step ,col_start:col-end,col-step]" for matrix slicing syntax

In [47]:
b[1:6]

array([[61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47]])

In [49]:
b[1:6:2,]

array([[61, 59, 55, 77, 69, 69, 48, 60],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [75, 67, 53, 77, 60, 67, 67, 47]])

In [51]:
b[1:6:2,1:6]

array([[59, 55, 77, 69, 69],
       [45, 52, 74, 65, 53],
       [67, 53, 77, 60, 67]])

In [53]:
b[2,1:6]

array([56, 51, 58, 59, 47])

In [55]:
b[2:5]

array([[71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51]])

In [57]:
b[3:6,2:6]

array([[52, 74, 65, 53],
       [46, 69, 65, 75],
       [53, 77, 60, 67]])

In [59]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [61]:
b[1:6:2]

array([[61, 59, 55, 77, 69, 69, 48, 60],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [75, 67, 53, 77, 60, 67, 67, 47]])

In [63]:
b[1:6:2, 1:8:3]

array([[59, 69, 60],
       [45, 65, 55],
       [67, 60, 47]])