In [1]:
from sklearn.ensemble import IsolationForest
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
data=sns.load_dataset("iris")
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [25]:
from scipy.stats import zscore
df=data.copy()
z_scores=np.abs(zscore(df.drop('species',axis=1)))

In [27]:
z_scores

sepal_length  sepal_width  petal_length  petal_width
0        0.900681     1.019004      1.340227     1.315444
1        1.143017     0.131979      1.340227     1.315444
2        1.385353     0.328414      1.397064     1.315444
3        1.506521     0.098217      1.283389     1.315444
4        1.021849     1.249201      1.340227     1.315444
..            ...          ...           ...          ...
145      1.038005     0.131979      0.819596     1.448832
146      0.553333     1.282963      0.705921     0.922303
147      0.795669     0.131979      0.819596     1.053935
148      0.432165     0.788808      0.933271     1.448832
149      0.068662     0.131979      0.762758     0.790671

[150 rows x 4 columns]

In [29]:
z_scores.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       0.833096     0.775262      0.888225     0.866315
std        0.554981     0.633756      0.460948     0.501171
min        0.052506     0.098217      0.023872     0.000878
25%        0.416010     0.328414      0.478571     0.395774
50%        0.795669     0.592373      1.018527     1.052180
75%        1.143017     1.200092      1.283389     1.315444
max        2.492019     3.090775      1.785832     1.712096

In [31]:
zscore(df.drop('species',axis=1))

sepal_length  sepal_width  petal_length  petal_width
0       -0.900681     1.019004     -1.340227    -1.315444
1       -1.143017    -0.131979     -1.340227    -1.315444
2       -1.385353     0.328414     -1.397064    -1.315444
3       -1.506521     0.098217     -1.283389    -1.315444
4       -1.021849     1.249201     -1.340227    -1.315444
..            ...          ...           ...          ...
145      1.038005    -0.131979      0.819596     1.448832
146      0.553333    -1.282963      0.705921     0.922303
147      0.795669    -0.131979      0.819596     1.053935
148      0.432165     0.788808      0.933271     1.448832
149      0.068662    -0.131979      0.762758     0.790671

[150 rows x 4 columns]

In [44]:
np.abs(zscore(df.drop('species',axis=1)))

sepal_length  sepal_width  petal_length  petal_width
0        0.900681     1.019004      1.340227     1.315444
1        1.143017     0.131979      1.340227     1.315444
2        1.385353     0.328414      1.397064     1.315444
3        1.506521     0.098217      1.283389     1.315444
4        1.021849     1.249201      1.340227     1.315444
..            ...          ...           ...          ...
145      1.038005     0.131979      0.819596     1.448832
146      0.553333     1.282963      0.705921     0.922303
147      0.795669     0.131979      0.819596     1.053935
148      0.432165     0.788808      0.933271     1.448832
149      0.068662     0.131979      0.762758     0.790671

[150 rows x 4 columns]

In [54]:
from scipy.stats import zscore

data=sns.load_dataset('iris')
df=data.copy()


In [56]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [50]:
z_scores=np.abs(zscore(df.drop('species',axis=1)))
z_scores

sepal_length  sepal_width  petal_length  petal_width
0        0.900681     1.019004      1.340227     1.315444
1        1.143017     0.131979      1.340227     1.315444
2        1.385353     0.328414      1.397064     1.315444
3        1.506521     0.098217      1.283389     1.315444
4        1.021849     1.249201      1.340227     1.315444
..            ...          ...           ...          ...
145      1.038005     0.131979      0.819596     1.448832
146      0.553333     1.282963      0.705921     0.922303
147      0.795669     0.131979      0.819596     1.053935
148      0.432165     0.788808      0.933271     1.448832
149      0.068662     0.131979      0.762758     0.790671

[150 rows x 4 columns]

In [52]:
z_scores.loc[10:15]

sepal_length  sepal_width  petal_length  petal_width
10      0.537178     1.479398      1.283389     1.315444
11      1.264185     0.788808      1.226552     1.315444
12      1.264185     0.131979      1.340227     1.447076
13      1.870024     0.131979      1.510739     1.447076
14      0.052506     2.169988      1.453901     1.315444
15      0.173674     3.090775      1.283389     1.052180

In [68]:
(z_scores<3).all(axis=1)

0      True
1      True
2      True
3      True
4      True
       ... 
145    True
146    True
147    True
148    True
149    True
Length: 150, dtype: bool

In [70]:
threshold=3
non_outliers=(z_scores<3).all(axis=1)
df_no_outliers=df[non_outliers]

In [72]:
df_no_outliers

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[149 rows x 5 columns]

In [74]:
outliers=(z_scores>3).any(axis=1)
outlier_rows=df[outliers]
outlier_rows

sepal_length  sepal_width  petal_length  petal_width species
15           5.7          4.4           1.5          0.4  setosa

In [76]:
from sklearn.ensemble import IsolationForest
import pandas as pd
import numpy as np
import seaborn as sns

In [78]:
data=sns.load_dataset("iris")
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [84]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
data['species']=lb.fit_transform(data['species'])


In [86]:
data.head(3)

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0

In [88]:
clf=IsolationForest(random_state=10)
clf.fit(data)

IsolationForest(random_state=10)

In [90]:
clf.predict(data)

array([ 1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1, -1, -1, -1, -1,
        1, -1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
        1,  1,  1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1,  1,  1,  1, -1,
        1, -1,  1,  1,  1,  1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1,
        1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1,
       -1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1, -1, -1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [92]:
clf=IsolationForest(random_state=10,contamination=0.01)
clf.fit(data)

IsolationForest(contamination=0.01, random_state=10)

In [94]:
clf.predict(data)

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [96]:
y_pred_outliers=clf.predict(data)
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [98]:
idx=np.where(y_pred_outliers==-1)
idx[0]

array([117, 131], dtype=int64)

In [100]:
data.drop(index=[117,131,118],axis=0)

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[147 rows x 5 columns]